#!/usr/bin/env bash

git_repos=$(find ~/src ~/usr -mindepth 1 -maxdepth 4 -type d -name .git -exec dirname {} \;)
git_bare_repos=$(find ~/src ~/usr -mindepth 1 -maxdepth 4 -type d -name worktrees -exec dirname {} \;)
selected=$(echo -e "$git_repos\n$git_bare_repos" | fzf)

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename $selected | sed "s/.git//g")
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t $selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
    exit 0
fi

tmux switch-client -t $selected_name
