#!/usr/bin/env bash

selected=$(find ~/src -mindepth 2 -maxdepth 3 -type d -name .git -exec dirname {} \; | cat - <(echo ".config/nvim") | fzf)

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | sed "s/.git//g" | sed "s/\./_/g")
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s "$selected_name" -c "$selected"
  exit 0
fi

if ! tmux has-session -t "$selected_name" 2>/dev/null; then
  tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $TMUX ]]; then
  tmux attach-session -t "$selected_name"
  exit 0
fi

tmux switch-client -t "$selected_name"
